In [112]:
import pandas as pd
import selenium 
from selenium import webdriver
import numpy as np
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - Downloading: 100%|██████████| 8.81M/8.81M [00:00<00:00, 49.1MB/s]


In [21]:
driver.get("https://www.opensecrets.org/industries/summary.php?ind=Q&cycle=2022&recipdetail=M&sortorder=U")

codes = []
industries = []

results = driver.find_elements_by_xpath('//*[@id="indus_switch"]')
for r in results:
    opt = r.find_elements_by_tag_name("option")
    for x in opt:
        codes.append(x.get_attribute("value")[:-2])
        industries.append(x.text)

In [88]:
codes = ['Q14', 'Q15', 'Q16', 'Z1200', 'J2100', 'Q02', 'Q11', 'Q04', 'Q12', 'Q13', 'Q09', 'Q03', 'J7300', 'Q05', 'Z1100', 'J2200', 'Q01', 'Q08']
industries = ['Abortion Policy/Anti-Abortion', 'Abortion Policy/Pro-Abortion Rights', 'Candidate Committees', 'Democratic Candidate Committees', 'Democratic leadership PAC', 'Democratic/Liberal', 'Environment', 'Foreign & Defense Policy', 'Gun Control', 'Gun Rights', 'Human Rights', 'Leadership PACs', 'LGBTQIA Rights & Issues', 'Pro-Israel', 'Republican Candidate Committees', 'Republican leadership PAC', 'Republican/Conservative', "Women's Issues"]
print(codes, industries)

['Q14', 'Q15', 'Q16', 'Z1200', 'J2100', 'Q02', 'Q11', 'Q04', 'Q12', 'Q13', 'Q09', 'Q03', 'J7300', 'Q05', 'Z1100', 'J2200', 'Q01', 'Q08'] ['Abortion Policy/Anti-Abortion', 'Abortion Policy/Pro-Abortion Rights', 'Candidate Committees', 'Democratic Candidate Committees', 'Democratic leadership PAC', 'Democratic/Liberal', 'Environment', 'Foreign & Defense Policy', 'Gun Control', 'Gun Rights', 'Human Rights', 'Leadership PACs', 'LGBTQIA Rights & Issues', 'Pro-Israel', 'Republican Candidate Committees', 'Republican leadership PAC', 'Republican/Conservative', "Women's Issues"]


In [93]:
links = ["https://www.opensecrets.org/industries/summary.php?ind=Q&cycle=2022&recipdetail=S&mem=N",
"https://www.opensecrets.org/industries/summary.php?ind=Q&cycle=2022&recipdetail=S&sortorder=A&mem=N&page=2",
"https://www.opensecrets.org/industries/summary.php?ind=Q&cycle=2022&recipdetail=S&sortorder=A&mem=N&page=3"]

sen_cd = []

for link in links:
    driver.get(link)


    results = driver.find_elements_by_xpath('//*[@id="profileLeftColumn"]/table')
    for r in results:
        opt = r.find_elements_by_tag_name("td")
        for i in range (len(opt)):
            if ((i%2==0) or (i%2==2)):
                sen_cd.append(opt[i].text)

sen_cd.sort()
print(sen_cd)

['Arkoosh, Val (D-PA)', 'Ayotte, Kelly (R-NH)', 'Baer, Dan (D-CO)', 'Baldwin, Tammy (D-WI)', 'Barnes, Mandela (D-WI)', 'Barnette, Kathy (R-PA)', 'Barrasso, John A (R-WY)', 'Bartos, Jeff (R-PA)', 'Bartos, Jeff (R-PA)', 'Battino, Gillian (D-WI)', 'Beasley, Cheri (D-NC)', 'Becker, Rick (R-ND)', 'Beebe, Rodney Jason (R-OR)', 'Bengs, Brian (D-SD)', 'Bennet, Michael (D-CO)', 'Bequette, Jake (R-AR)', 'Beyer, Brad (R-WI)', 'Black, Gary (R-GA)', 'Blackburn, Marsha (R-TN)', 'Blanchard, Lynda (R-AL)', 'Blumenthal, Richard (D-CT)', 'Blunt, Roy (R-MO)', 'Bolduc, Don (R-NH)', 'Bollier, Barbara (D-KS)', 'Booker, Charles (D-KY)', 'Booker, Cory (D-NJ)', 'Boozman, John (R-AR)', 'Bourn, Brenda (R-ID)', 'Bradley, James (R-CA)', 'Bradshaw, Marquita (D-TN)', 'Braun, Mike (R-IN)', 'Bremer, Eli (R-CO)', 'Britt, Katie Boyd (R-AL)', 'Brnovich, Mark Mr. (R-AZ)', 'Brooks, Mo (R-AL)', 'Brown, Sam (R-NV)', 'Brown, Scott (R-NH)', 'Brown, Sherrod (D-OH)', 'Bruce, Catherine (D-SC)', 'Budd, Ted (R-NC)', 'Bullock, Steve

In [94]:
candidate_df = pd.DataFrame(columns=industries)

In [95]:
candidate_df.insert(0, "Candidates", sen_cd)

In [96]:
candidate_df

Candidates Abortion Policy/Anti-Abortion  \
0           Arkoosh, Val (D-PA)                           NaN   
1          Ayotte, Kelly (R-NH)                           NaN   
2              Baer, Dan (D-CO)                           NaN   
3         Baldwin, Tammy (D-WI)                           NaN   
4        Barnes, Mandela (D-WI)                           NaN   
..                          ...                           ...   
255  Whitehouse, Sheldon (D-RI)                           NaN   
256        Wicker, Roger (R-MS)                           NaN   
257     Williams, Cordie (R-CA)                           NaN   
258           Wyden, Ron (D-OR)                           NaN   
259          Young, Todd (R-IN)                           NaN   

    Abortion Policy/Pro-Abortion Rights Candidate Committees  \
0                                   NaN                  NaN   
1                                   NaN                  NaN   
2                                   NaN                  NaN   
3                                   NaN                  NaN   
4                                   NaN                  NaN   
..                                  ...                  ...   
255                                 NaN                  NaN   
256                                 NaN                  NaN   
257                                 NaN                  NaN   
258                                 NaN                  NaN   
259                                 NaN                  NaN   

    Democratic Candidate Committees Democratic leadership PAC  \
0                               NaN                       NaN   
1                               NaN                       NaN   
2                               NaN                       NaN   
3                               NaN                       NaN   
4                               NaN                       NaN   
..                              ...                       ...   
255                             NaN                       NaN   
256                             NaN                       NaN   
257                             NaN                       NaN   
258                             NaN                       NaN   
259                             NaN                       NaN   

    Democratic/Liberal Environment Foreign & Defense Policy Gun Control  \
0                  NaN         NaN                      NaN         NaN   
1                  NaN         NaN                      NaN         NaN   
2                  NaN         NaN                      NaN         NaN   
3                  NaN         NaN                      NaN         NaN   
4                  NaN         NaN                      NaN         NaN   
..                 ...         ...                      ...         ...   
255                NaN         NaN                      NaN         NaN   
256                NaN         NaN                      NaN         NaN   
257                NaN         NaN                      NaN         NaN   
258                NaN         NaN                      NaN         NaN   
259                NaN         NaN                      NaN         NaN   

    Gun Rights Human Rights Leadership PACs LGBTQIA Rights & Issues  \
0          NaN          NaN             NaN                     NaN   
1          NaN          NaN             NaN                     NaN   
2          NaN          NaN             NaN                     NaN   
3          NaN          NaN             NaN                     NaN   
4          NaN          NaN             NaN                     NaN   
..         ...          ...             ...                     ...   
255        NaN          NaN             NaN                     NaN   
256        NaN          NaN             NaN                     NaN   
257        NaN          NaN             NaN                     NaN   
258        NaN          NaN             NaN                     NaN   
259     

In [97]:
def scrape(code, page, industry):
    
    
    
    link = "https://www.opensecrets.org/industries/summary.php?ind=" + code + "&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=" + str(page)
    print(link)
    driver.get(link)
    
    totals = []
    
    driver.implicitly_wait(2)
    results = driver.find_elements_by_xpath('//*[@id="profileLeftColumn"]/table')
    for r in results:
        opt = r.find_elements_by_tag_name("td")
        for i in range (len(opt)):
            if (i%2==0):
                print(opt[i])
                ind = np.where(candidate_df["Candidates"] == opt[i].text)
                print(ind)
                amt = (opt[i+1].text[1:]).replace(",", "")
                print(amt)
                candidate_df.at[candidate_df.index[ind[0]], industry] = int(amt)

In [98]:
for i in range (len(codes)):
    code = codes[i]
    industry = industries[i]
        
    
    for n in range(1,4):
        scrape(code, n, industry)
        
    #candidate_df[industry] = totals

https://www.opensecrets.org/industries/summary.php?ind=Q14&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="33f08985-fd16-460d-88c2-6170cca03e65")>
(array([5]),)
7900
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e9a4a67b-fd9c-4d95-b0b3-7c25488606fb")>
(array([22]),)
5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="0b9243ea-fe51-4d7a-acc0-5b25c0108e82")>
(array([26]),)
3662
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="5343bcdf-54c0-402e-bcd9-4450b5b1cd35")>
(array([32]),)
5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="bbf38547-a5ef-49f3-94ef-1c194c768b70")>
(array([39]),)
27981
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53f

(array([96]),)
102244
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="0aca2a47-a9fe-47c0-9139-caf7e79d1d06")>
(array([101]),)
55
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8a95fadd-01cd-4bba-ba5b-66cbaca85fd3")>
(array([107]),)
250
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="19b062f5-0200-44b5-b639-bc77682acdae")>
(array([122]),)
120215
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="f5956ec3-b8da-4a71-ac67-2af74cfb8e64")>
(array([130]),)
1500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="6419c7c2-3932-4a5b-9847-df25b272c1f9")>
(array([133]),)
1500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="3bfde03c-a92d-45ab-b25b-1ae3ba7caa19")>
(array([137]),)


2177
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="afafb838-624a-471b-a31f-fb1ef08b245a")>
(array([63]),)
6114
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a04516b9-0e58-425d-a6f3-f281a3592d2f")>
(array([64]),)
6000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="c19ca402-e44e-4b2a-b294-7366ea1f2ceb")>
(array([66]),)
59706
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="6f401129-12d2-4cd9-9ef5-e0bbfa3d8f4a")>
(array([68]),)
18401
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8e7694c3-5098-4cc6-adfa-89b40839a188")>
(array([70]),)
4000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="aa9d86d6-0c92-48a7-98e1-e78f3dffaecd")>
(array([75]),)
19160
<selenium.webd

(array([147]),)
-6000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8b2d537a-a52f-45b9-83a7-95f629e7af4c")>
(array([149]),)
3000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="147173e1-e3a5-4b53-ab3b-d4a719e3a65b")>
(array([150]),)
1150
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="c8d3873d-78de-49f6-92fd-0fe97ddf8f84")>
(array([151]),)
1500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e1a9db36-fc4d-41d0-aac1-4997043ec1ea")>
(array([152]),)
2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="763e03b2-c74c-4bb0-a4f5-96d14a0241b5")>
(array([153]),)
11000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="2253e960-38c0-471b-9d0a-77340b2f5f0e")>
(array([154]),

(array([222]),)
1500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="6495f9ed-1389-4c8c-955a-11f7a23d450a")>
(array([224]),)
-334
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8687d928-1ca3-4c76-a997-e756b6e726dc")>
(array([227]),)
9000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="47ce3e1d-c677-4610-aa66-26312ccdc710")>
(array([228]),)
3000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="10827b32-5a95-4f56-80cf-d76f6ac1980b")>
(array([230]),)
500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1f068e7a-204a-484e-894f-ea84f8605ec2")>
(array([231]),)
4000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="4066ab09-adb4-4672-9a58-988b25dd0995")>
(array([232]),)
1

-4000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="317468e4-6476-4bd3-acb6-088118d20de5")>
(array([99]),)
2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8b4434ce-e4c2-490a-8154-181e07f856b7")>
(array([100]),)
-2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a212df2b-db2b-4df7-a7e6-90763014bb5e")>
(array([101]),)
810
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="400eccac-a3df-4b2c-8998-404f3db163d9")>
(array([102]),)
4000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="fc55015e-acdf-4cc5-9287-d1730e9a488c")>
(array([106]),)
2500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8d03ef65-5de7-445b-878b-1cd4f9d77342")>
(array([107]),)
2000
<selenium.w

(array([253]),)
2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="66b0a90c-849d-4bcc-8dfb-62d20218ab06")>
(array([255]),)
1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="f93205c3-5724-4653-96c7-c0643b0844a0")>
(array([258]),)
6500
https://www.opensecrets.org/industries/summary.php?ind=Z1200&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=2
https://www.opensecrets.org/industries/summary.php?ind=Z1200&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=J2100&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="727097a2-e189-43a5-90c0-f5fdce2d77cb")>
(array([0]),)
5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b8e2cce3-a927-4b85-9b6a-2a46d345504e")>
(array([3]),)

(array([216]),)
225000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="d26ef551-7d68-4850-a909-37409bc1354c")>
(array([219]),)
193900
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="acc8ee53-dbae-4dc9-81f0-0891ae597449")>
(array([227]),)
30000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1d48dab7-d01d-439b-8b21-d184f204e30e")>
(array([231]),)
42500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="48cf4972-3dfd-495f-94ef-1ead864c15d3")>
(array([237]),)
50000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a021fa6c-b98b-447e-ac72-a88118291bc0")>
(array([244]),)
364400
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="dd65d1be-6797-4301-b80a-4662af40cfeb")>
(array(

250
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="cac3f797-3ffa-4e0f-83a9-1308b6c17cb1")>
(array([117]),)
75
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="947e32be-a913-4d97-a5d3-d604ce93d5f8")>
(array([119]),)
28225
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b522b79c-551b-4bb8-bb44-c79a91488378")>
(array([122]),)
1480216
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="88228f66-7e2c-45e7-9723-4cbcad7d15e6")>
(array([125]),)
2978
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="414e57e9-bc57-44e7-ae80-33c7890dab05")>
(array([126]),)
1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1b48224e-ee91-40c7-a12b-27d81bee5738")>
(array([130]),)
7025
<selenium.

https://www.opensecrets.org/industries/summary.php?ind=Q02&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=Q11&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1edbdca3-1ef3-427f-8035-345da2b49686")>
(array([0]),)
1800
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="96b68b36-9fe7-497a-98a6-75b59efe395c")>
(array([3]),)
3235
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="43ac2f26-4102-42fd-a6ba-c4f75e129478")>
(array([4]),)
61535
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a1dd8d56-d20d-45fa-a5e3-07e4332e61a9")>
(array([6]),)
2900
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="eaf4c5d6-dc5c-4a0a-bd91-0f9a5e

(array([125]),)
5800
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1c7d842c-014e-488a-af3b-08ac51a36d12")>
(array([130]),)
10050
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e3df441e-a6c3-4209-b88f-3a4f7e7887b1")>
(array([131]),)
6958
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="964970fe-83f8-432a-924c-983b6be7307c")>
(array([133]),)
-9600
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a62083fd-a920-4299-99d2-a8114736fe3b")>
(array([139]),)
-1750
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="d48335b5-e430-47b2-b8bb-74783f2d2ec1")>
(array([140]),)
2900
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="5a2132dd-aa68-458a-86a0-cb3b1dc3657c")>
(array([141])

https://www.opensecrets.org/industries/summary.php?ind=Q11&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=Q04&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="92d8c794-b077-4ab4-901e-03aeab0a8987")>
(array([2]),)
-287
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e2e10269-45ec-419c-a787-532561eaf1a9")>
(array([4]),)
4150
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1242694e-cbe1-4db0-8968-0aaa2a747cb5")>
(array([10]),)
12060
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="f330104a-da8a-4dcc-aa8d-05c0dd6680ee")>
(array([14]),)
43733
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="19935b0c-4ef1-4599-b5e2-67f

https://www.opensecrets.org/industries/summary.php?ind=Q04&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1ff0ccb6-85ff-42a5-a6ae-3eebcc9b9870")>
(array([4]),)
19733
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="286764e8-29b5-4e7f-badd-8241afa8d3f4")>
(array([10]),)
46264
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a2c1c148-02e2-4c8a-9301-2887e3b2f547")>
(array([14]),)
21590
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="3cbdf74c-a632-4e0a-936d-eca3a267a0e1")>
(array([20]),)
53795
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="ead2ea84-1c0f-4972-afe3-

(array([153]),)
58567
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="0e425004-7a26-43d4-a7e9-acae9a0bf67d")>
(array([157]),)
1175
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a8f2ba5c-77e4-423d-9307-b899049bf067")>
(array([173]),)
15969
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="35e1fb0d-8a96-44d9-8464-a97b29641175")>
(array([178]),)
20853
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="4d34f18d-0109-4a7d-92cf-d624974629b9")>
(array([179]),)
11871
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="567369ee-57f6-4681-9fe8-02cc865aeb7f")>
(array([185]),)
16650
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a114641c-b953-4ff7-acc8-9bfd73e36b8d")>
(array([191

(array([93]),)
10090
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="5c9d0ad6-d46b-4e75-a2a0-3fa9a88ce029")>
(array([96]),)
215284
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="7303c765-9082-44bd-afeb-ab0edf1eb2c8")>
(array([98]),)
-5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e732e908-4693-446a-a81d-3443260dea00")>
(array([102]),)
11840
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="41986ffe-f3b2-4170-9726-9d195c14a21f")>
(array([109]),)
250
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="7879fc44-a84c-4e17-8350-b1f6e395c8b2")>
(array([111]),)
2500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="11559874-a900-4ee5-82df-09b47f0f2357")>
(array([117]),)

(array([223]),)
2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="437eb120-1b90-402f-b8b7-7fbd69ce0b30")>
(array([225]),)
1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="5c70dc5c-1502-4c75-a93a-b4613acb2d17")>
(array([227]),)
-690
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e4704a1f-69f9-4ad1-90b1-3554dbdcb427")>
(array([229]),)
500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="4114a098-395f-4623-8e48-5c9efc89230f")>
(array([230]),)
1350
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="671a226d-361a-4111-a4a6-a3e86274c1cb")>
(array([231]),)
13709
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="e853e00a-fe6e-4d25-af04-c0a0ec2617b2")>
(array([233]),)


-5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="c6c4c192-2719-4b40-b7e4-4cc850371810")>
(array([55]),)
500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a2c84ea1-11fe-447f-a648-bdf0b385694b")>
(array([57]),)
1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="657aad45-34fa-4076-bbe3-1fa4a30be64b")>
(array([58]),)
500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b4e4c4fd-1664-483a-853c-46f77a1c644f")>
(array([61]),)
65000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="233a86df-1fe6-42c9-8a2b-7d9535df43a4")>
(array([62]),)
364200
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="880954af-749e-4310-ad5d-547d31c4041c")>
(array([63]),)
30000
<selenium.webd

-26925
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b2a9da6c-40de-4d24-9502-003098c67781")>
(array([144]),)
100350
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="046715c8-d4d3-455d-9d7c-6ed0f1d963de")>
(array([145]),)
794
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="4da70408-ce42-44eb-a3b4-f847d9dbda50")>
(array([146]),)
25000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="d81d62e8-48b5-41b6-a8a7-8c4893fe20e5")>
(array([148]),)
15500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="d09e8a59-b5f5-44b1-afe0-911110002638")>
(array([149]),)
23500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="cf23d092-b515-4c1c-8548-75d2d52b371f")>
(array([150]),)
21000
<sel

52500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="098601de-9834-48c5-a7a1-914fc54a1bcf")>
(array([234]),)
1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="4b9f9308-66be-4a6e-85c0-78c2fb73cf34")>
(array([237]),)
51000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="7c14d305-9f17-4afc-85f8-f9aff41b025b")>
(array([238]),)
330500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="0278284a-cefd-4062-ab29-005d232885c3")>
(array([239]),)
5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8fa143a0-5d79-45b6-a0a6-fcb82187cc06")>
(array([240]),)
35500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="66aa4b1a-b6e5-4bbe-9782-7417cda4776a")>
(array([242]),)
13900
<sele

(array([39]),)
144156
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="983406a3-d508-4317-aee8-ca6dc961103c")>
(array([58]),)
400
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="aebad942-e0a2-46dc-8a79-793431f39557")>
(array([62]),)
139059
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="705911d4-dbd3-44ca-8a1d-bcc4d7ff88aa")>
(array([66]),)
19562
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="96f76246-c223-46d1-b06e-a6e56af52812")>
(array([68]),)
229100
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="1f8e8969-c7a7-4108-bb1c-7a88319db7c6")>
(array([70]),)
1250
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="49c02df2-f564-4f0e-8c40-799aa7685303")>
(array([75]),)
2

(array([238]),)
229382
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="653d853d-a00d-45a3-8638-5de50e8f99e4")>
(array([242]),)
2000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="41d69021-9e10-44a1-8f25-dea6b94f910b")>
(array([244]),)
54230
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="da581c22-9175-4195-a513-d120ddf9ad77")>
(array([245]),)
167324
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="900162d8-94d2-4157-81ad-4dd472248b06")>
(array([247]),)
63176
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="8613bd58-c96e-4288-9883-d3e13ec1c7e8")>
(array([249]),)
12900
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="03a70b4f-495f-4132-9da9-8dbc3388f3a7")>
(array([2

100
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="3a6b1880-9e24-49cf-98e3-75d6fa7a7342")>
(array([173]),)
7500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="393c1f5b-e17f-42a3-9c9e-158224c3123b")>
(array([176]),)
-1000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="0dc30b9c-bec9-4b07-be13-7e782e275f07")>
(array([178]),)
36800
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a030674c-9455-4049-b829-0ede012c6ad7")>
(array([179]),)
5000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="ec403091-68fd-43e9-8a57-43335252c8a2")>
(array([185]),)
5171
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="f0979ad1-766c-4497-a462-391a9fae52c0")>
(array([191]),)
21000
<selenium

391700
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="5ebc444c-c193-47bd-baf1-7905ba85d7ab")>
(array([92]),)
27500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="340f57a6-93a7-4550-8f05-8a313e30d338")>
(array([95]),)
153000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="47533236-dda9-408b-8e85-04460a05005d")>
(array([97]),)
30000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="efdabf5c-bdbb-4c74-97d2-5547e4811702")>
(array([103]),)
248500
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="feeda649-ab35-4629-ad99-db00ead58d4f")>
(array([105]),)
56000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="27756775-de53-4cd0-95b3-4ca99b031897")>
(array([117]),)
383000
<se

262500
https://www.opensecrets.org/industries/summary.php?ind=J2200&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=2
https://www.opensecrets.org/industries/summary.php?ind=J2200&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=Q01&cycle=2022&recipdetail=S&sortorder=N&mem=N&page=1
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b6d64eff-f773-4e52-8329-91c78bebaf42")>
(array([5]),)
109023
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="05742027-419e-4424-8f21-35d61da0df33")>
(array([6]),)
44055
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="7a8d17ca-cb2d-4679-878a-66f4dd0ce1da")>
(array([7, 8]),)
-105561
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="6199d829-cc54-4656-9ba0-e791fce2c7e6")>
(array([11]),)
8850
<sel

(array([97]),)
1541524
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="dea8ec96-9e19-48de-91b4-dd1ffde56792")>
(array([103]),)
39488
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="3186c2ab-7383-4668-af21-d61420647b78")>
(array([105]),)
1100
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="d18d04be-f764-4e79-9fd1-0d1d74c51a20")>
(array([106]),)
425
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="66a20357-d375-471c-94c1-dbd3c4d03aba")>
(array([110]),)
250
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="6cf085e0-7c78-4ed9-860e-da3dd5b0026c")>
(array([111]),)
-351
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="95abed7a-5751-4ba5-a062-54352584a974")>
(array([112]),)

9790
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="939bc7f1-d333-4082-a2fa-fd8de364d1cd")>
(array([198]),)
21655
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="eb201e6c-ed2e-4034-8e07-bd8b421d77a1")>
(array([200]),)
-30750
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="91214ab7-4472-4b7e-b783-0d18d3770534")>
(array([201]),)
5800
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="15a132d3-35e9-4ff4-9c9f-37f986381af1")>
(array([204]),)
2674
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="44290863-f29b-4c0f-94e2-9cb550fbb75f")>
(array([205]),)
15590
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="96661784-5a1b-41ee-bfc6-6d955c00472b")>
(array([207]),)
-5366
<selen

(array([75]),)
5697
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="217768dc-de38-46cf-be0a-baee89d5e8f6")>
(array([77]),)
126572
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="b08a445a-038d-4ff7-a00f-b139b66be765")>
(array([80]),)
85
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="24f8b9e4-9b31-4a79-83b7-834f5ca44bbb")>
(array([84]),)
3000
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="95386ec4-4f0e-4f83-b4ff-8e5fb733399f")>
(array([85]),)
182285
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="c3e51c32-e8ad-45a4-b7ae-abe6a98b112e")>
(array([95]),)
13150
<selenium.webdriver.remote.webelement.WebElement (session="71a6e74755c06d53fa308bc4f2feac01", element="a94f3989-1da3-42d5-b6e6-a26d0e6e2f33")>
(array([96]),)
1241

In [81]:
candidate_df

Candidates Abortion Policy/Anti-Abortion  \
0           Arkoosh, Val (D-PA)                           NaN   
1          Ayotte, Kelly (R-NH)                           NaN   
2              Baer, Dan (D-CO)                           NaN   
3         Baldwin, Tammy (D-WI)                           NaN   
4        Barnes, Mandela (D-WI)                           NaN   
..                          ...                           ...   
255  Whitehouse, Sheldon (D-RI)                           NaN   
256        Wicker, Roger (R-MS)                           NaN   
257     Williams, Cordie (R-CA)                           NaN   
258           Wyden, Ron (D-OR)                           NaN   
259          Young, Todd (R-IN)                            66   

    Abortion Policy/Pro-Abortion Rights Candidate Committees  \
0                                   500                 4000   
1                                   NaN                -1000   
2                                   NaN                  NaN   
3                                   300                 8000   
4                                 65799                34900   
..                                  ...                  ...   
255                                 NaN                 1000   
256                                 NaN                 2000   
257                                 NaN                  NaN   
258                                2362                 6500   
259                                 NaN                 7000   

    Democratic Candidate Committees Democratic leadership PAC  \
0                              4000                      5000   
1                               NaN                       NaN   
2                               NaN                       NaN   
3                              8000                     60000   
4                             34900                    443500   
..                              ...                       ...   
255                            1000                     75390   
256                             NaN                       NaN   
257                             NaN                       NaN   
258                            6500                    271500   
259                             NaN                       NaN   

    Democratic/Liberal Environment Foreign & Defense Policy Gun Control  \
0                -8014        1800                      NaN         NaN   
1                  NaN         NaN                      NaN         NaN   
2                  NaN         NaN                     -287         NaN   
3               254550        3235                      NaN         NaN   
4               661334       61535                     4150       19733   
..                 ...         ...                      ...         ...   
255              24900        9364                      NaN         NaN   
256                NaN         NaN                      NaN         NaN   
257                NaN         NaN                      NaN         NaN   
258             281238       68967                      NaN       10900   
259             227420        5900                     1000         NaN   

    Gun Rights Human Rights Leadership PACs LGBTQIA Rights & Issues  \
0          NaN         7529            5000                     NaN   
1          NaN          NaN             NaN                     NaN   
2          NaN         -575             NaN                     NaN   
3          NaN         1100           80000                    1025   
4          NaN       154977          454150                   21719   
..         ...          ...             ...                     ...   
255        NaN           50           76390                     NaN   
256        NaN          NaN          200500                     NaN   
257        NaN          NaN             NaN                     NaN   
258        NaN       105222          282000                   18672   
259     

In [99]:
candidate_df = candidate_df.fillna(0)

In [100]:
candidate_df.to_csv('senate.csv')

In [106]:
h_link = "https://www.opensecrets.org/industries/summary.php?ind=Q03&cycle=2022&recipdetail=H&sortorder=N&mem=N&page="

house_cd = []

for i in range(1,9):
    driver.get(h_link + str(i))


    results = driver.find_elements_by_xpath('//*[@id="profileLeftColumn"]/table')
    for r in results:
        opt = r.find_elements_by_tag_name("td")
        for i in range (len(opt)):
            if ((i%2==0) or (i%2==2)):
                house_cd.append(opt[i].text)

house_cd.sort()
print(house_cd)

['Aadland, Erik (R-CO)', 'Adams, Alma (D-NC)', 'Aderholt, Robert B (R-AL)', 'Adkins, Amanda (R-KS)', 'Aiken, Clay (D-NC)', 'Alexander, Timothy C (D-NJ)', 'Alford, Mark (R-MO)', 'Allam, Nida (D-NC)', 'Allcorn, Tyler (R-CO)', 'Allen, Richard W (R-GA)', 'Allred, Colin (D-TX)', 'Almonord, Val (D-GA)', 'Alonso Leon, Teresa (D-OR)', 'Ambrose, Mark (R-MI)', 'Ambrose, Nicolee (R-MD)', 'Amodei, Mark (R-NV)', 'Anderson, Derrick (R-VA)', 'Andrews, Annie (D-SC)', 'Arballo, Phil (D-CA)', 'Armendariz-Jackson, Irene (R-TX)', 'Armstrong, Kelly (R-ND)', 'Arrington, Jodey (R-TX)', 'Asencio, Robert (D-FL)', 'Auchincloss, Jake (D-MA)', 'Axne, Cindy (D-IA)', 'Babin, Brian (R-TX)', 'Bacon, Donald John (R-NE)', 'Bailey, Richard (R-CA)', 'Baird, Jim (R-IN)', 'Balderson, Troy (R-OH)', 'Balint, Becca (D-VT)', 'Banks, Jim (R-IN)', 'Barnes-Israel, Stu (R-IN)', 'Barr, Andy (R-KY)', 'Barr, Timothy (R-GA)', 'Barragan, Nanette (D-CA)', 'Barrett, Tom (R-MI)', 'Basler, Doug (R-WA)', 'Baugh, Scott (R-CA)', 'Baxter, Tim 

In [107]:
house_df = pd.DataFrame(columns=industries)
house_df.insert(0, "Candidates", house_cd)

In [118]:
def h_scrape(code, page, industry):
    
    
    
    link = "https://www.opensecrets.org/industries/summary.php?ind=" + code + "&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=" + str(page)
    print(link)
    driver.get(link)
    
    totals = []
    
    driver.implicitly_wait(1)
    results = driver.find_elements_by_xpath('//*[@id="profileLeftColumn"]/table')
    for r in results:
        if (r.text == ""):            
            break
        else:
            opt = r.find_elements_by_tag_name("td")
            for i in range (len(opt)):
                if (i%2==0):
                    ind = np.where(house_df["Candidates"] == opt[i].text)
                    amt = (opt[i+1].text[1:]).replace(",", "")
                    print(amt)
                    house_df.at[house_df.index[ind[0]], industry] = int(amt)

h_scrape("Q14", 10, "Abortion Policy/Anti-Abortion")

https://www.opensecrets.org/industries/summary.php?ind=Q14&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=10


In [119]:
for i in range (len(codes)):
    code = codes[i]
    industry = industries[i]
        
    
    for n in range(1,9):
        h_scrape(code, n, industry)

https://www.opensecrets.org/industries/summary.php?ind=Q14&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=1
500
16068
500
500
500
500
8579
500
500
524
500
7418
2768
5768
6000
500
1000
2000
1150
500
500
9145
7768
500
500
1750
500
500
500
5768
16750
1500
515
2000
500
500
500
30
13300
11018
500
500
500
500
3018
500
500
37218
6000
500
500
500
3000
5010
5000
7300
200
500
500
5000
8949
500
500
1250
27950
1550
2675
500
500
700
5000
23168
17125
5000
5520
13578
500
1000
500
500
2500
500
500
33493
500
500
500
500
500
2725
3150
4533
5000
5000
26750
500
2768
6650
500
7900
6000
500
500
500
500
8275
5000
500
500
500
3877
500
500
500
5518
1500
3387
26493
7000
3900
https://www.opensecrets.org/industries/summary.php?ind=Q14&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=2
6000
600
500
500
11818
500
500
5250
7100
1768
1750
5000
500
500
500
8268
7800
5768
500
500
500
3000
500
2815
500
1500
2210
8150
400
500
12500
1000
500
5000
500
500
500
500
9483
2536
1250
5000
500
7575
5600
500
1660
8668
500
500
5768

2000
12000
5000
10000
6678
50000
2800
1007
4000
77144
12000
https://www.opensecrets.org/industries/summary.php?ind=Q16&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=7
6000
1000
1000
14000
13000
-4000
27000
104036
12000
4000
13000
41000
260
11500
2000
2000
8000
7000
55250
14000
106660
40500
2900
71251
77501
4000
12000
68990
18000
24500
15000
52000
14500
4000
2000
250
24000
12000
2000
500
500
2000
65000
51500
195
-500
-2900
8000
1000
42500
11000
7000
9120
4456
-9600
2278
9000
7100
2000
-3000
86850
2000
14000
1000
4750
1000
1000
6000
16000
6000
12000
19500
9500
12994
86502
4000
69000
61499
13500
40000
48000
107
57500
56000
12500
53500
-8000
4000
3299
1000
2000
-8000
28500
12000
250
4000
7500
2000
250
2900
2900
12000
12000
17500
2000
3100
33500
10000
44900
2000
6982
460
151401
2573
23500
50
9000
3000
4000
14001
https://www.opensecrets.org/industries/summary.php?ind=Q16&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=8
2000
420
10000
9500
11500
2000
2000
24500
1420
25000
15000
60000
77750

122724
-250
6000
6500
1368
777
27850
39500
1000
250
81961
20700
2090
111522
19000
27855
6664
2700
7800
500
33495
94297
5500
87854
125822
-44071
10431
142275
27609
14621
-17667
119603
20159
35081
22400
14200
5595
5350
24291
8870
1250
2150
16910
7300
2895
6466
5250
72816
244806
66300
48696
45875
73902
131368
187835
134900
13050
6
15500
500
1500
22625
49605
7500
16100
-116
1030
7500
281290
5000
18210
10000
1790
156550
25738
62914
5750
1000
13500
17325
3755
20600
93766
7008
1000
11300
264418
190376
695
79635
251
47867
7430
5823
1775
7070
4400
4332
9425
90960
18132
11550
2000
42100
25
50541
62188
5000
3148
88889
8575
29279
1000
1000
61416
132970
21600
20924
20565
2900
https://www.opensecrets.org/industries/summary.php?ind=Q02&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=3
191929
239896
81480
272091
2900
3900
65600
15
2500
62445
8401
132023
-968
6400
29938
98840
10100
7500
13150
3230
5000
14200
17530
80472
438588
500
10500
14911
271486
750
82510
250
8250
43371
250
-2800
418831
45155
99905

25210
5500
14235
-900
2450
1000
14637
1000
2000
2000
3750
2000
3500
1000
250
4450
1000
1000
1000
9075
5000
2000
2000
14000
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=2
3
250
1000
1125
15550
500
-12389
2000
1500
1000
26940
2072
1000
2250
13076
3900
4250
3050
4527
2000
1000
2902
1000
1000
1250
5900
47739
3260
12150
18300
3009
9200
12940
2750
12050
4500
14420
13678
14705
7900
1000
499
-500
2040
1000
4400
4150
2000
1000
1250
1000
11643
5000
1560
3500
25100
18700
2000
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=3
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=4
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=5
https://www.opensecrets.org/industries/summary.php?ind=Q12&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=6
https://www.opensecrets.org/indu

8699
2000
37500
13000
177303
22000
5496
10000
330600
231500
147451
2500
73500
9500
5000
1000
8500
116000
31000
268100
-2000
19000
2000
29800
7000
48500
30400
12000
38500
3500
4000
71900
19000
7900
-1500
14500
7500
32500
1500
61000
9500
142100
1000
14000
67001
64900
8000
21000
175426
410435
128200
63500
42400
2000
7912
35500
10500
103600
10800
-4000
48300
94500
5000
13000
361425
53400
2000
33000
108800
240900
2000
1000
3500
255500
27900
99750
77185
3500
7500
4500
2500
130677
142800
1000
2500
4000
17500
27900
3000
7000
62000
2500
3500
1000
88000
2500
13750
9150
142950
28756
81500
115400
10000
1000
50000
41500
10900
1000
71800
41000
52400
2500
61500
13301
2500
50000
2500
40500
40500
42352
https://www.opensecrets.org/industries/summary.php?ind=Q03&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=3
15900
55500
102954
1000
216550
51600
190349
190200
57400
52000
305600
39500
69500
82896
103502
1340
460300
10000
1000
10500
5000
1000
43300
237402
51500
118200
69000
47500
55500
2000
2000
2000
165

1000
3150
8200
16700
10500
61292
12751
19900
-1000
1350
4712
12450
6500
33450
17900
10750
5500
14125
7900
44750
43946
6000
10193
15250
71906
26450
31666
13800
12500
9800
65617
426455
32850
99660
10000
19960
12800
9400
6900
88300
50500
250
5000
40650
7800
5250
76427
75700
22777
8500
20800
4150
2750
96562
93046
1000
13700
12645
29780
115781
6500
2500
488632
1000
82150
20200
10500
12200
2250
4250
12750
37700
10000
3000
19000
24200
2200
5000
27850
125794
37906
500
11000
46450
10000
134445
44201
10000
10000
11650
41300
3650
21749
107510
36500
8900
25487
276791
14640
22200
13500
26100
45481
689487
40230
756695
5000
https://www.opensecrets.org/industries/summary.php?ind=Q05&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=3
13200
12900
50875
3250
59525
26550
47126
8200
439790
22400
19000
2000
30750
76290
7900
14797
59850
2500
21010
51150
41525
61650
23545
16450
21525
7900
45575
4900
90946
13500
50350
127880
112596
3800
36103
26725
8250
11690
1000
61400
1000
37863
38650
5800
44950
500
8900
4700

86500
49500
149000
1000
74300
33500
54000
69500
73100
43000
166200
5500
55900
4000
228900
37500
71900
19000
22100
2500
47800
85500
53000
51000
35500
45900
2500
141600
25500
1000
35500
34400
52700
297700
47000
6000
123500
1500
46100
170150
30500
77940
8500
3500
28500
6000
44500
8000
31000
1000
4000
19500
109700
24001
5000
148600
37000
38900
21500
55000
120600
22900
5000
44900
-1000
26500
24000
49000
36000
42300
74500
78000
392250
6900
1500
19500
1500
5500
2500
26500
82600
2000
95800
41750
2000
7000
23000
69000
39400
61300
15502
49000
42900
8000
4000
1000
263200
68400
6000
157400
1000
99500
58900
19000
33000
22000
10000
29400
131400
84000
19500
30500
91400
18500
https://www.opensecrets.org/industries/summary.php?ind=J2200&cycle=2022&recipdetail=H&sortorder=N&mem=N&page=4
26500
33700
40500
27500
-500
103800
2000
7000
57000
303550
56500
115500
46000
25800
50800
6900
15000
65000
2000
-1000
55300
161000
2500
33224
29500
63000
29000
43400
337450
62700
122700
152500
159100
1000
180500
39000
27

In [120]:
house_df

Candidates Abortion Policy/Anti-Abortion  \
0             Aadland, Erik (R-CO)                           NaN   
1               Adams, Alma (D-NC)                           NaN   
2        Aderholt, Robert B (R-AL)                           500   
3            Adkins, Amanda (R-KS)                         16068   
4               Aiken, Clay (D-NC)                           NaN   
..                             ...                           ...   
881              Young, Don (R-AK)                           NaN   
882             Zeldin, Lee (R-NY)                           NaN   
883  Zimm, Christian Gerard (R-GA)                           NaN   
884       Zimmerman, Robert (D-NY)                           NaN   
885             Zinke, Ryan (R-MT)                           NaN   

    Abortion Policy/Pro-Abortion Rights Candidate Committees  \
0                                   NaN                16000   
1                                   500                12900   
2                                   NaN                10000   
3                                   NaN                50650   
4                                   NaN                 2000   
..                                  ...                  ...   
881                                 NaN                  NaN   
882                                 NaN                15000   
883                                 NaN                  NaN   
884                                7500                60000   
885                                 NaN                77750   

    Democratic Candidate Committees Democratic leadership PAC  \
0                               NaN                       NaN   
1                             12900                     18250   
2                               NaN                       NaN   
3                               NaN                       NaN   
4                              2000                      4000   
..                              ...                       ...   
881                             NaN                       NaN   
882                             NaN                       NaN   
883                             NaN                       NaN   
884                           60000                    110400   
885                             NaN                       NaN   

    Democratic/Liberal Environment Foreign & Defense Policy Gun Control  \
0                  NaN         NaN                      NaN         NaN   
1                 9400         NaN                      NaN         NaN   
2                  NaN         NaN                      NaN         NaN   
3                  NaN         NaN                     4400         NaN   
4                -3230        1000                      NaN         NaN   
..                 ...         ...                      ...         ...   
881                NaN         NaN                      NaN         NaN   
882                NaN         NaN                      NaN         NaN   
883                NaN         NaN                      NaN         NaN   
884             112583        7500                     2900         NaN   
885                500         NaN                      NaN         NaN   

    Gun Rights Human Rights Leadership PACs LGBTQIA Rights & Issues  \
0          NaN          NaN           67500                     NaN   
1          NaN         2462           18250                      12   
2        12243          NaN           40500                     NaN   
3        15839          NaN          259550                     NaN   
4          NaN         8681            4000                    8181   
..         ...          ...             ...                     ...   
881       5750          NaN           17500                     NaN   
882        NaN          200           63700                     NaN   
883        NaN          NaN            2000                     NaN   
884        NaN        48041          113300   

In [121]:
house_df = house_df.fillna(0)
house_df

Candidates  Abortion Policy/Anti-Abortion  \
0             Aadland, Erik (R-CO)                              0   
1               Adams, Alma (D-NC)                              0   
2        Aderholt, Robert B (R-AL)                            500   
3            Adkins, Amanda (R-KS)                          16068   
4               Aiken, Clay (D-NC)                              0   
..                             ...                            ...   
881              Young, Don (R-AK)                              0   
882             Zeldin, Lee (R-NY)                              0   
883  Zimm, Christian Gerard (R-GA)                              0   
884       Zimmerman, Robert (D-NY)                              0   
885             Zinke, Ryan (R-MT)                              0   

     Abortion Policy/Pro-Abortion Rights  Candidate Committees  \
0                                      0                 16000   
1                                    500                 12900   
2                                      0                 10000   
3                                      0                 50650   
4                                      0                  2000   
..                                   ...                   ...   
881                                    0                     0   
882                                    0                 15000   
883                                    0                     0   
884                                 7500                 60000   
885                                    0                 77750   

     Democratic Candidate Committees  Democratic leadership PAC  \
0                                  0                          0   
1                              12900                      18250   
2                                  0                          0   
3                                  0                          0   
4                               2000                       4000   
..                               ...                        ...   
881                                0                          0   
882                                0                          0   
883                                0                          0   
884                            60000                     110400   
885                                0                          0   

     Democratic/Liberal  Environment  Foreign & Defense Policy  Gun Control  \
0                     0            0                         0            0   
1                  9400            0                         0            0   
2                     0            0                         0            0   
3                     0            0                      4400            0   
4                 -3230         1000                         0            0   
..                  ...          ...                       ...          ...   
881                   0            0                         0            0   
882                   0            0                         0            0   
883                   0            0                         0            0   
884              112583         7500                      2900            0   
885                 500            0                         0            0   

     Gun Rights  Human Rights  Leadership PACs  LGBTQIA Rights & Issues  \
0             0             0            67500                        0   
1             0          2462            18250                       12   
2         12243             0            40500                        0   
3         15839             0           259550                        0   
4             0          8681             4000                     8181   
..          ...           ...              ...                      ...   
881        5750             0            17500                        0   
882           0           200            63700  

In [122]:
house_df.to_csv("house.csv")

In [118]:
driver.get("https://ballotpedia.org/Election_results,_2022:_Congressional_margin_of_victory_analysis")

results = driver.find_elements_by_class_name("marqueetable")import re

table = results[2].find_elements_by_tag_name('tr')

for r in table:
    cols = r.find_elements_by_tag_name('td')
    for i in range len()
        try:
            print(cols[2].text, int(re.sub(",", "", cols[3].text)), cols[4].text, cols[5].text)
        except:
            continue
        
        

[<selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_39")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_40")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_41")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_42")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_43")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857", element="C84AB072A5AC112AB295A4B8B2D35347_element_44")>, <selenium.webdriver.remote.webelement.WebElement (session="9bef84901df918d9a9d23d46a8d76857",

Katie Britt 940054 Will Boyd 435,431
Lisa Murkowski 135972 Kelly Tshibaka 117,299
Mark Kelly 1322027 Blake Masters 1,196,308
John Boozman 587990 Natalie James 276,792
Alex Padilla 3202616 Mark Meuser 2,213,091
Michael Bennet 1397170 Joe O'Dea 1,031,693
Richard Blumenthal 723864 Leora Levy 535,943
Marco Rubio 4474847 Val Demings 3,201,522
Raphael Warnock 1820633 Herschel Walker 1,721,244
Brian Schatz 227825 Bob McDermott 69,155
Mike Crapo 54745 David Roth 47,225
Tammy Duckworth 2329136 Kathy Salvi 1,701,055
Todd Young 1090390 Thomas McDermott Jr. 704,480
Chuck Grassley 672242 Michael Franken 519,094
Jerry Moran 602976 Mark R. Holland 372,214
Rand Paul 910397 Charles Booker 562,928
John Neely Kennedy 822298 Gary Chambers 235,077
Chris Van Hollen 922821 Chris Chaffee 593,153
Eric Schmitt 785330 Trudy Busch Valentine 579,166
Catherine Cortez Masto 481659 Adam Laxalt 476,676
Maggie Hassan 298351 Don Bolduc 243,583
Chuck Schumer 3189890 Joe Pinion 2,441,975
Ted Budd 1887701 Cheri Beasley 1,7

In [109]:
len(results)

280

In [46]:
print (results[0].text)

Average MOV for Congressional elections, 2012-2018
Chamber 2012 2014 2016 2018
U.S. Senate 20% 22.6% 22.1% 16.8%
U.S. House 31.9% 35.8% 36.6% 30.2%
